### ISSUE TITLE
[Feature Request] Ability to bind mouse axes to a virtual analog stick

### ISSUE THREAD

**Issue by boomercore** [schellingb/GamepadPhoenix#5]
It may seem silly, but this would be godsend for Tempest 2K in BigPemu and Tempest 4000 which only support analog sticks instead of mice and spinners.  Virtual Controller https://sourceforge.net/projects/vjoy-controller has this functionality but it's quite unstable.  Thanks in advance.

**Comment by schellingb** [comment]
Hey there, thanks for the suggestion! I don't think it's that silly :-)

The [just released version 0.9.5](https://schelling.itch.io/gamepad-phoenix/purchase) adds support to [map every mouse function to any gamepad part](../#mousekeyboard-inputs). When movement is mapped to an analog stick, the also newly added [deadzone settings](../#deadzone-settings) can be used to customize how much movement is needed to fully tilt the emulated gamepad stick. It is suggested to use a high setting for "Max Limit" and a low setting for "Sensitivity" to reduce the required movement. For mouse inputs the "Sensitivity" deadzone setting controls how slow/fast the stick centers itself back when stopping mouse movement.

Can you check that out and report back how well this works for you?

**Comment by boomercore** [comment]
Thank you for working on this.  Phoenix seems to interact a bit strangely with BigPEmu, though. With the mouse bound to the left stick and no physical game controllers plugged in, BigPEmu will claim that JOY-H135 is held down, even when I'm not touching it.  It will pick up JOY-A128/129 when I move the mouse, but as soon as I stop moving it'll revert back to JOY-H135 being detected.  It's like Phoenix is sending something extra to it.  I have no other binds but mouse x/y to the appropriate left stick directions.  Tried both Xinput and Dinput exclusively, same result.  Tried binding all other inputs to the same key just to see if that would override some button it was sending, didn't help.  When I completely clear all binds and leave it idle after launching BigPEmu through Phoenix, it won't show this JOY-H135.

Upon further testing, it will do this when I bind anything from any input device to any of the virtual stick axes/buttons. 
![mysteryinput](https://user-images.githubusercontent.com/30274474/229310847-574c3c1c-e53f-408e-97e9-63cd9553b59b.png)

**Comment by schellingb** [comment]
Very interesting. I also get the "JOY-H135 being still held" message.
So it seems BigPEmu sees these things (no idea where it has the numbers from):
- A128 = Horizontal axis of left analog stick
- A129 = Vertical axis of left analog stick
- A130 = Left analog trigger
- A131 = Horizontal axis of right analog stick
- A132 = Vertical axis of right analog stick
- A133 = Right analog trigger
- H134 = The DPAD, also known as "Hat Switch" in DirectInput
- H135 = ??? This would be a second "Hat Switch" but Gamepad Phoenix should not expose such a feature on the emulated DirectInput gamepad.

A very basic tool I use for testing the DirectInput emulation is "Pointy's Joystick Test Application" from http://www.planetpointy.co.uk/joystick-test-application/
But unlike BigPEmu that tool correctly detects only one "Hat Switch".
I'll look some more into this tomorrow. I'm very curious now :-)
Thanks for the quick response and details, I saw it before the edit ;-)

**Comment by boomercore** [comment]
Alright, yeah, glad you could reproduce it.  I wanted to be sure it was happening on just one more machine as I have some unorthodox Dualshock drivers installed and was wondering if they could be part of the problem.  Happened on the other machine too.  One more thing of note, the mouse-to-joystick functionality only seems to work when I run BigPEmu windowed.  Also, when I toggle POVtoButtons, H134 is detected instead of H135.

**Comment by schellingb** [comment]
I think I figured it out! BigPEmu uses DirectInput in some way where it defines the data format instead of using the data as offered. And with that it defines a data format for a joystick that that has 16 analog sticks and 4 d-pads (POV hat switches). Up until now Gamepad Phoenix just responded with a value 0 for these superfluous objects but for DirectInput the default value for a unpressed d-pad is -1 and not 0 so BigPEmu saw the 3 extra d-pads as always being up (value = 0) instead of unpressed (value = -1).
Before I push a new version, can you give this special build that includes these fixes a shot?
[GamepadPhoenix-0.9.5fix6321fdf.zip](https://github.com/schellingb/GamepadPhoenix/files/11132460/GamepadPhoenix-0.9.5fix6321fdf.zip)

Also once you can play Temptest with this, are you able to make the mouse controls feel good or do you think the available deadzone settings are insufficient? There is some magic under the hood how the mouse controlled analog stick goes back to the center which I wasn't really sure if the user needs even more fine control.

**Comment by boomercore** [comment]
Sorry for letting this rot.  The game has since added native support for this and the feature seems to work well enough outside of my odd request.  This is great software though, and I use it on the regular.  Thanks again for looking into it.
